name: '$(Date:yyyyMMdd)$(Rev:.r)'

variables: 
  - name: 'toolsVersion'
    value: ''
  - name: 'checksumx86'
    value: ''
  - name: 'checksumx64'
    value: ''

jobs:
  - job: 'build_choco_package'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - powershell: |
          $release = Invoke-RestMethod -Method Get -Uri 'https://api.github.com/repos/Azure/azure-functions-core-tools/releases/latest'
          $toolsVersion = $release.name
          Write-Output ("##vso[task.setvariable variable=toolsVersion;]$toolsVersion")
          $hash86 = invoke-webrequest "https://github.com/Azure/azure-functions-core-tools/releases/download/$toolsVersion/Azure.Functions.Cli.win-x86.$toolsversion.zip.sha2"
          Write-Output ("##vso[task.setvariable variable=checksumx86;]$([text.encoding]::utf8.getstring($hash86.Content))")
          $hash64 = invoke-webrequest "https://github.com/Azure/azure-functions-core-tools/releases/download/$toolsVersion/Azure.Functions.Cli.win-x64.$toolsversion.zip.sha2"
          Write-Output ("##vso[task.setvariable variable=checksumx64;]$([text.encoding]::utf8.getstring($hash64.Content))")
        displayName: 'Get Current Release Version + Checksums'
      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: 'Replace Tokens in nuspec and ps1'
        inputs:
          targetFiles: '**\?(*.nuspec|*.ps1)'
      - script: choco pack --outputdirectory $(Build.ArtifactStagingDirectory)
        displayName: 'Get Current Release Version'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
          artifactName: 'chocolatey'
          publishLocation: 'Container'